sonar.projectKey=amex-bta-portal
sonar.projectName=AMEX BTA Portal
sonar.projectVersion=1.0

sonar.sources=src
sonar.exclusions=**/*.spec.ts,**/node_modules/**
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.javascript.lcov.reportPaths=../../coverage/apps/bta-portal/lcov.info

sonar.sourceEncoding=UTF-8
