# Activate with: --spring.profiles.active=postgres
# Only need to: install postgres + CREATE DATABASE wearablesdb;
# Tables + seed data are handled automatically by Flyway.

spring.datasource.url=jdbc:postgresql://localhost:5432/wearablesdb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.h2.console.enabled=false
spring.flyway.enabled=true